# Generated by Django 3.1.2 on 2020-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AddField(
            model_name='lugar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
