# Generated by Django 3.1.2 on 2020-11-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnboardApp', '0004_auto_20201104_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='estrellas',
            field=models.IntegerField(choices=[[0, '1 estrella'], [1, '2 estrellas'], [2, '3 estrellas'], [3, '4 estrellas'], [4, '5 estrellas']]),
        ),
    ]
