# Generated by Django 3.1.2 on 2020-11-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnboardApp', '0005_auto_20201104_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='estrellas',
            field=models.IntegerField(choices=[[0, '1 Estrella'], [1, '2 Estrellas'], [2, '3 Estrellas'], [3, '4 Estrellas'], [4, '5 Estrellas']]),
        ),
    ]
